# Generated by Django 3.2.16 on 2022-12-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221220_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='images/blank-profile-picture-g603ac37a8_640_pzvogy.png', upload_to='images/'),
        ),
    ]
