# Generated by Django 3.2.16 on 2022-12-28 12:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='Required. 150 characters or fewer. May only contain letters and digits.', max_length=150, unique=True, validators=[accounts.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
