# Generated by Django 3.2.16 on 2022-12-28 12:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. May only contain letters and digits.', max_length=150, unique=True, validators=[accounts.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
