# Generated by Django 3.2.16 on 2022-12-28 12:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Required. 30 characters or fewer. May only contain letters and digits.', 'unique': 'A user with that username already exists'}, help_text='Required. 30 characters or fewer. May only contain letters and digits.', max_length=30, unique=True, validators=[accounts.models.UsernameValidator()], verbose_name='username'),
        ),
    ]
